name: Deploy Databricks Bundle

on:
  push:
    branches:
      - main
      - uat
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST_MASTER }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_MASTER }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks -v

      - name: Install uv
        run: pip install uv

      - name: Set target from branch
        id: set_target
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          echo "target=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "Deploy target is $BRANCH_NAME"

      - name: Validate bundle
        run: databricks bundle validate -t ${{ steps.set_target.outputs.target }}

      - name: Deploy bundle
        run: databricks bundle deploy -t ${{ steps.set_target.outputs.target }}